---
title: "using_tb"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{using_tb}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(piptb)
```


# Basic use
```{r basic, eval=FALSE}
dt <- pipload::pip_load_cache("PRY", year = 2019, tool = "TB")

# Basic use. mean default
tb(dt,
   vars = "welfare_ppp", 
   weight = "weight")[]

# Basic use. by area and gender
tb(dt,
   vars = "welfare_ppp", 
   weight = "weight", 
   col   = "area", 
   row   = "gender")[]


# Poverty status
tb(dt,
   vars = "pov_status", 
   weight = "weight", 
   col   = "area", 
   row   = "gender")[]


# Poverty status and welfare
tb(dt,
   vars = c("pov_status", "welfare_ppp", "welfare_lcu"), 
   weight = "weight", 
   col   = "area", 
   row   = "gender")[]

# Poverty status and welfare, mean, sum,and max
# sum for poor is the number of people
tb(dt,
   vars = c("pov_status", "welfare_ppp"), 
   weight = "weight", 
   col   = "area", 
   row   = "gender", 
   stats = c("mean", "sum", "max"))[]


# Add more poverty lines
tb(dt,
   vars = c("pov_status", "welfare_ppp"), 
   weight = "weight", 
   col   = "area", 
   row   = "gender", 
   stats = c("mean", "sum"), 
   povlines = c(1.9, 3.2, 5.5))[]



# add super column
tb(dt,
   vars = c("welfare_ppp"), 
   weight = "weight", 
   col   = "area", 
   row   = "gender", 
   scol  = "educat4")[]

# add super row
tb(dt,
   vars = c("welfare_ppp"), 
   weight = "weight", 
   col   = "area", 
   row   = "gender", 
   scol  = "educat4",
   srow  = "literacy")[]

# Size of population (vars = NULL)
tb(dt,
   # vars = "pov_status", 
   weight = "weight", 
   col   = "area", 
   row   = "gender", 
   stats = "sum", 
   by_survey = TRUE)[]

```


# BIG data

```{r big-setup, eval=FALSE}
dt <- pipload::pip_load_cache("COL", tool = "TB")
```


```{r big-cals, eval=FALSE}

# Basic use. mean default
system.time({
   tb(dt,
      vars = "welfare_ppp", 
      weight = "weight")
})

# Basic use. by area and gender
system.time({
   tb(dt,
      vars = "welfare_ppp", 
      weight = "weight", 
      col   = "area", 
      row   = "gender")
})


# Poverty status
system.time({
   tb(dt,
      vars = "pov_status", 
      weight = "weight", 
      col   = "area", 
      row   = "gender")
})


# Poverty status and welfare
system.time({
   
tb(dt,
   vars = c("pov_status", "welfare_ppp", "welfare_lcu"), 
   weight = "weight", 
   col   = "area", 
   row   = "gender")
   
})

# Poverty status and welfare, mean, sum,and max
# sum for poor is the number of people
system.time({
   
tb(dt,
   vars = c("pov_status", "welfare_ppp"), 
   weight = "weight", 
   col   = "area", 
   row   = "gender", 
   stats = c("mean", "sum", "max"))
})


# Add more poverty lines
system.time({
   
tb(dt,
   vars = c("pov_status", "welfare_ppp"), 
   weight = "weight", 
   col   = "area", 
   row   = "gender", 
   stats = c("mean", "sum"), 
   povline = c(1.9, 3.2, 5.5))
   
})



# add super column
system.time({
   
tb(dt,
   vars = c("welfare_ppp"), 
   weight = "weight", 
   col   = "area", 
   row   = "gender", 
   scol  = "educat4")
   
})

# add super row
system.time({
   
tb(dt,
   vars = c("welfare_ppp"), 
   weight = "weight", 
   col   = "area", 
   row   = "gender", 
   scol  = "educat4",
   srow  = "literacy")
   
})

# Size of population (vars = NULL)
system.time({
   
tb(dt,
   # vars = "pov_status", 
   weight = "weight", 
   col   = "area", 
   row   = "gender", 
   stats = "sum", 
   by_survey = TRUE)
   
})

```

# Benchmarking

This is the code to create the benchmarking. It is not executed in this vignette.

```{r bench, eval=FALSE}

# The whole process
di <- pipload::pip_find_cache("COL", tool = "TB")

fdl <- function(di) {
  dl <- pipload::pip_load_cache(cache_id = di, 
                                type = "list", 
                                verbose = FALSE, 
                                pipedir = "e:/PovcalNet/01.personal/wb384996/temp/R/")
  rl <- purrr::map(dl, ~{
    tb(.data = .x,
       vars = "welfare_ppp", 
       weight = "weight", 
       col   = "area", 
       row   = "gender", 
       stats = "mean")
  })
}


fdt <- function(di) {
  dt <- pipload::pip_load_cache(cache_id = di, 
                                verbose = FALSE, 
                                pipedir = "e:/PovcalNet/01.personal/wb384996/temp/R/")
  rt <- tb(.data = dt,
           vars = "welfare_ppp", 
           weight = "weight", 
           col   = "area", 
           row   = "gender", 
           stats = "mean")
  
  rt <- split(rt, rt[, "ID"])
}


bench <- microbenchmark::microbenchmark(
  times = 50,
  a_all = fdt(di),
  b_all = fdl(di)
)

if (requireNamespace("highcharter")) {
  library(magrittr)
  hc_dt <- highcharter::data_to_boxplot(bench,
                                        time,
                                        expr,
                                        add_outliers = FALSE,
                                        name = "Time in milliseconds")
  
  highcharter::highchart() %>%
    highcharter::hc_xAxis(type = "category") %>%
    highcharter::hc_chart(inverted=TRUE) %>% 
    highcharter::hc_add_series_list(hc_dt)
  
} else {
  boxplot(bench, outline = FALSE)
}


# loading 
bench <- microbenchmark::microbenchmark(
  times = 50,
  a_load = pipload::pip_load_cache(cache_id = di, 
                               verbose = FALSE, 
                               pipedir = "e:/PovcalNet/01.personal/wb384996/temp/R/"),
  b_load = pipload::pip_load_cache(cache_id = di, 
                               type = "list", 
                               verbose = FALSE, 
                               pipedir = "e:/PovcalNet/01.personal/wb384996/temp/R/")
)

if (requireNamespace("highcharter")) {
  library(magrittr)
  hc_dt <- highcharter::data_to_boxplot(bench,
                                        time,
                                        expr,
                                        add_outliers = FALSE,
                                        name = "Time in milliseconds")
  
  highcharter::highchart() %>%
    highcharter::hc_xAxis(type = "category") %>%
    highcharter::hc_chart(inverted=TRUE) %>% 
    highcharter::hc_add_series_list(hc_dt)
  
} else {
  boxplot(bench, outline = FALSE)
}

# calculations

# di <- pipload::pip_find_cache("COL", tool = "TB")

dl <- pipload::pip_load_cache(cache_id = di,
                                type = "list",
                                verbose = FALSE, 
                              pipedir = "e:/PovcalNet/01.personal/wb384996/temp/R/")

dt <- pipload::pip_load_cache(cache_id = di,
                              verbose = FALSE, 
                              pipedir = "e:/PovcalNet/01.personal/wb384996/temp/R/")

bench <- microbenchmark::microbenchmark(
  times = 50,
  a_calc = {
    rt <- tb(.data = dt,
             vars = "welfare_ppp", 
             weight = "weight", 
             col   = "area", 
             row   = "gender", 
             stats = "mean", 
             by_survey = TRUE)
    
    rt <- split(rt, rt[, "ID"])
  },
  b_calc = {
    rl <- purrr::map(dl, ~{
    tb(.data = .x,
       vars = "welfare_ppp", 
       weight = "weight", 
       col   = "area", 
       row   = "gender", 
       stats = "mean")
  })
  }
)

if (requireNamespace("highcharter")) {
  library(magrittr)
  hc_dt <- highcharter::data_to_boxplot(bench,
                                        time,
                                        expr,
                                        add_outliers = FALSE,
                                        name = "Time in milliseconds")
  
  highcharter::highchart() %>%
    highcharter::hc_xAxis(type = "category") %>%
    highcharter::hc_chart(inverted=TRUE) %>% 
    highcharter::hc_add_series_list(hc_dt)
  
} else {
  boxplot(bench, outline = FALSE)
}
# pushoverr::pushover("Done with benchmarking")


```
